<?php

/**
 * BaseDocumentVersion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $document_id
 * @property string $file
 * @property Document $Document
 * 
 * @method integer         getDocumentId()  Returns the current record's "document_id" value
 * @method string          getFile()        Returns the current record's "file" value
 * @method Document        getDocument()    Returns the current record's "Document" value
 * @method DocumentVersion setDocumentId()  Sets the current record's "document_id" value
 * @method DocumentVersion setFile()        Sets the current record's "file" value
 * @method DocumentVersion setDocument()    Sets the current record's "Document" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseDocumentVersion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('document_version');
        $this->hasColumn('document_id', 'integer', null, array(
             'notnull' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('file', 'string', 255, array(
             'notnull' => true,
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Document', array(
             'local' => 'document_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}