<?php

/**
 * BaseDocument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $description
 * @property string $file
 * @property boolean $public
 * @property Doctrine_Collection $Categories
 * @property Doctrine_Collection $Tags
 * @property Doctrine_Collection $Users
 * 
 * @method string              getTitle()       Returns the current record's "title" value
 * @method clob                getDescription() Returns the current record's "description" value
 * @method string              getFile()        Returns the current record's "file" value
 * @method boolean             getPublic()      Returns the current record's "public" value
 * @method Doctrine_Collection getCategories()  Returns the current record's "Categories" collection
 * @method Doctrine_Collection getTags()        Returns the current record's "Tags" collection
 * @method Doctrine_Collection getUsers()       Returns the current record's "Users" collection
 * @method Document            setTitle()       Sets the current record's "title" value
 * @method Document            setDescription() Sets the current record's "description" value
 * @method Document            setFile()        Sets the current record's "file" value
 * @method Document            setPublic()      Sets the current record's "public" value
 * @method Document            setCategories()  Sets the current record's "Categories" collection
 * @method Document            setTags()        Sets the current record's "Tags" collection
 * @method Document            setUsers()       Sets the current record's "Users" collection
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6670 2009-11-04 19:52:45Z jwage $
 */
abstract class BaseDocument extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('document');
        $this->hasColumn('title', 'string', 255, array(
             'notnull' => true,
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('file', 'string', 255, array(
             'notnull' => true,
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('public', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Category as Categories', array(
             'refClass' => 'DocumentCategory',
             'local' => 'document_id',
             'foreign' => 'category_id'));

        $this->hasMany('Tag as Tags', array(
             'refClass' => 'DocumentTag',
             'local' => 'document_id',
             'foreign' => 'tag_id'));

        $this->hasMany('User as Users', array(
             'refClass' => 'UserDocument',
             'local' => 'document_id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'version',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             'deleteVersions' => false,
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $versionable0->addChild($timestampable1);
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
              2 => 'file',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($versionable0);
        $this->actAs($sluggable0);
        $this->actAs($searchable0);
    }
}