<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property Doctrine_Collection $Documents
 * @property Doctrine_Collection $DocumentTag
 * 
 * @method string              getTitle()       Returns the current record's "title" value
 * @method Doctrine_Collection getDocuments()   Returns the current record's "Documents" collection
 * @method Doctrine_Collection getDocumentTag() Returns the current record's "DocumentTag" collection
 * @method Tag                 setTitle()       Sets the current record's "title" value
 * @method Tag                 setDocuments()   Sets the current record's "Documents" collection
 * @method Tag                 setDocumentTag() Sets the current record's "DocumentTag" collection
 * 
 * @package    dockeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('title', 'string', 255, array(
             'notnull' => true,
             'type' => 'string',
             'unique' => true,
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Document as Documents', array(
             'refClass' => 'DocumentTag',
             'local' => 'tag_id',
             'foreign' => 'document_id'));

        $this->hasMany('DocumentTag', array(
             'local' => 'id',
             'foreign' => 'tag_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'unique' => true,
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}