<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $username
 * @property string $password
 * @property string $salt
 * @property string $email
 * @property Doctrine_Collection $Categories
 * @property Doctrine_Collection $Documents
 * 
 * @method string              getUsername()   Returns the current record's "username" value
 * @method string              getPassword()   Returns the current record's "password" value
 * @method string              getSalt()       Returns the current record's "salt" value
 * @method string              getEmail()      Returns the current record's "email" value
 * @method Doctrine_Collection getCategories() Returns the current record's "Categories" collection
 * @method Doctrine_Collection getDocuments()  Returns the current record's "Documents" collection
 * @method User                setUsername()   Sets the current record's "username" value
 * @method User                setPassword()   Sets the current record's "password" value
 * @method User                setSalt()       Sets the current record's "salt" value
 * @method User                setEmail()      Sets the current record's "email" value
 * @method User                setCategories() Sets the current record's "Categories" collection
 * @method User                setDocuments()  Sets the current record's "Documents" collection
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6670 2009-11-04 19:52:45Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('username', 'string', 255, array(
             'notnull' => true,
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('password', 'string', 255, array(
             'notnull' => true,
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('salt', 'string', 255, array(
             'notnull' => true,
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'notnull' => true,
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Category as Categories', array(
             'refClass' => 'UserCategory',
             'local' => 'user_id',
             'foreign' => 'category_id'));

        $this->hasMany('Document as Documents', array(
             'refClass' => 'UserDocument',
             'local' => 'user_id',
             'foreign' => 'document_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'username',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}