<?php

/**
 * BaseUserDocument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $document_id
 * @property integer $user_id
 * 
 * @method integer      getDocumentId()  Returns the current record's "document_id" value
 * @method integer      getUserId()      Returns the current record's "user_id" value
 * @method UserDocument setDocumentId()  Sets the current record's "document_id" value
 * @method UserDocument setUserId()      Sets the current record's "user_id" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6670 2009-11-04 19:52:45Z jwage $
 */
abstract class BaseUserDocument extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_document');
        $this->hasColumn('document_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}