<?php

/**
 * BaseLibrary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $host
 * @property string $prefix
 * 
 * @method string  getName()   Returns the current record's "name" value
 * @method string  getHost()   Returns the current record's "host" value
 * @method string  getPrefix() Returns the current record's "prefix" value
 * @method Library setName()   Sets the current record's "name" value
 * @method Library setHost()   Sets the current record's "host" value
 * @method Library setPrefix() Sets the current record's "prefix" value
 * 
 * @package    dockeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLibrary extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('library');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('host', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('prefix', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('host_unique', array(
             'fields' => 
             array(
              0 => 'host',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}