<?php

/**
 * Admin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dockeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin extends BaseAdmin
{
  /**
   * Return the login of the Admin
   * @return string
   */
  public function __toString ()
  {
    return $this->login;
  }
  
	/**
	 * Check login password
	 * @param string $password
	 * @return boolean
	 */
	public function login ($password)
	{
    return (sha1($this->salt . $password) === $this->password);
	}

  /**
   * Encrypte the password
   * @param string $password
   */
  public function setPassword ($password)
  {
    if (!$password && 0 == strlen($password))
    {
      return;
    }
    
    $this->salt = sha1(date('r'));
    parent::_set('password', sha1($this->salt . $password));
  }
}
