<?php

/**
 * DocumentTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dockeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6508 2009-10-14 06:28:49Z jwage $
 */
class DocumentTag extends BaseDocumentTag
{
    /**
     * Empty template method to provide concrete Record classes with the possibility
     * to hook into the deletion procedure.
     */
    public function postDelete($event)
    {
	    if (0 === Doctrine::getTable('DocumentTag')->createQuery('d')->where('d.tag_id = ?', $this->tag_id)->count())
	    {
	      $this->Tag->delete();
	    }
    }
}
