<?php

/**
 * Library
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dockeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Library extends BaseLibrary
{
	/**
	 * Creates tables
	 * @param Doctrine_Event $event
	 */
	public function postSave($event)
	{
		$doctrine_connection_mysql = Doctrine_Manager::getInstance()->connection();
		if (!$doctrine_connection_mysql instanceof Doctrine_Connection_Common) throw new sfException(sprintf("Doctrine_Connection_Common excepected, %s given.", get_class($doctrine_connection_mysql)));
		$fichier_sql = new SplFileObject(sfConfig::get('sf_root_dir') . "/data/sql/schema.sql");
		while (!$fichier_sql->eof())
		{
			$ligne_sql = $fichier_sql->fgets();
			if (empty($ligne_sql) || false !== strpos('TABLE admin', $ligne_sql) || false !== strpos($ligne_sql, 'TABLE library')) continue;
			$ligne_sql = str_replace(array('TABLE ', 'REFERENCES ', 'CONSTRAINT '),  array('TABLE ' . $this->prefix . '_', 'REFERENCES ' . $this->prefix . '_', 'CONSTRAINT ' . $this->prefix . '_'), $ligne_sql);
		  $doctrine_connection_mysql->execute($ligne_sql);
		}
	}
}
