homepage:
  url:   /
  param: { module: category, action: index }
  class: frontendRoute

default_index:
  url:   /:module
  param: { action: index }
  class: frontendRoute

default:
  url:   /:module/:action/*
  class: frontendRoute
  
