#!/bin/sh

E_BADARGS=65

if [ $# -ne 1 ]
then
  echo "Usage: `basename $0` {user}"
  exit $E_BADARGS
fi

stty -echo
echo "Mot de passe :"
read PASSWD
stty echo


# Mise à jour
svn export --username $1 --password $PASSWD https://dockeet.googlecode.com/svn/trunk/update_svn ./update_svn --force
svn export --username $1 --password $PASSWD https://dockeet.googlecode.com/svn/trunk/web ./web --force
svn export --username $1 --password $PASSWD https://dockeet.googlecode.com/svn/trunk/apps ./apps --force
svn export --username $1 --password $PASSWD https://dockeet.googlecode.com/svn/trunk/data ./data --force
svn export --username $1 --password $PASSWD https://dockeet.googlecode.com/svn/trunk/lib ./lib --force
svn export --username $1 --password $PASSWD https://dockeet.googlecode.com/svn/trunk/plugins ./plugins --force
svn export --username $1 --password $PASSWD https://dockeet.googlecode.com/svn/trunk/config/doctrine ./config/doctrine --force
