generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Library
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          library
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Libraries - Dockeet backend
        display: [=prefix, name, host]
      filter:
        display: [name, host, prefix]
      form:    ~
      edit:
        title: Edit library - Dockeet backend
        display: [name, host, prefix]
      new:
        title: New library - Dockeet backend
        display: [name, host, prefix]