<?php

/**
 * Document
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    dockeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6508 2009-10-14 06:28:49Z jwage $
 */
class Document extends BaseDocument
{
	/**
	 * Path where files are saved
   * @param integer $version_id
	 * @return string
	 */
	public function getFilePath($version_id = null)
	{
		if (sfContext::hasInstance() && sfContext::getInstance()->has('library')) $library = sfContext::getInstance()->get('library');
		$prefix = ($library instanceof Library) ? '/' . $library->prefix : '';
	  $file_path = sfConfig::get('sf_upload_dir') . $prefix . '/documents/' . substr(str_pad($this->id, 2, '0', STR_PAD_LEFT), -2) . '/';
	  if (null === $version_id)
	  {
	    $file_path .= $this->file;
	  }
	  else
	  {
	    $version = Doctrine::getTable('DocumentVersion')->find($version_id);
	    $file_path .= $version->file;
	  }
    return $file_path;
	}

	/**
	 * Delete document and files
	 * @param unknown_type $event
	 */
  public function postDelete($event)
  {
    if (file_exists($this->getFilePath()))
    {
      unlink($this->getFilePath());
    }
  }

  /**
   * Save old file
   * @param unknown_type $event
   */
  public function preSave($event)
  {
    if (in_array('file', $this->_modified, true))
    {
      $document_version = new DocumentVersion();
      $document_version->document_id = $this->id;
      $document_version->file = $this->file;
      $document_version->mime_type = $this->mime_type;

      $this->Versions[] = $document_version;
    }
  }

  /**
   * Test if the user has subscribed to this document update
   * @param User $user
   * @return boolean
   */
  public function hasSubscribed (User $user)
  {
    $query_has_subscribed  = Doctrine::getTable('UserDocument')->createQuery('u')->where('u.user_id = ? AND u.document_id = ?');
    return 1 === $query_has_subscribed->count(array($user->id, $this->id));
  }

  /**
   * User subscription
   * @param User $user
   */
  public function subscribe (User $user)
  {
    $user_document = Doctrine::getTable('UserDocument')->createQuery('u')->where('document_id = ? AND user_id = ?', array($this->id, $user->id))->fetchOne();

    if (!$user_document instanceof UserDocument)
    {
      $user_document = new UserDocument();
      $user_document->Document= $this;
      $user_document->User = $user;
    }

    $user_document->save();
  }

  /**
   * User unsubscription
   * @param User $user
   */
  public function unsubscribe (User $user)
  {
    $user_document = Doctrine::getTable('UserDocument')->createQuery('u')->where('document_id = ? AND user_id = ?', array($this->id, $user->id))->fetchOne();

    if (!$user_document instanceof UserDocument)
    {
      throw new sfException('No relation between Document ' . $this->title . ' and user ' . $user->username);
    }

    $user_document->delete();
  }

  /**
   * Return the director where thumbnail of this document are saved
   * @return string
   */
  public function getThumbnailDirectory ()
  {
    if (sfContext::hasInstance() && sfContext::getInstance()->has('library')) $library = sfContext::getInstance()->get('library');
    $prefix = ($library instanceof Library) ? '/' . $library->prefix : '';
    return sfConfig::get('sf_upload_dir') . $prefix . '/thumbnail/' . substr(str_pad($this->id, 2, '0', STR_PAD_LEFT), -2) . '/';
  }

  /**
   * Return the url of the Thumbnail
   * @param integer $width
   * @param integer $height
   * @return string
   */
  public function getThumbnailUrl ($width, $height = null, $dont_check = false)
  {
    $height = (null === $height) ? $width : $height;
    $thumbnail_web_directory = str_replace(sfConfig::get('sf_web_dir'), '', $this->getThumbnailDirectory());
    $thumbnail_url = $thumbnail_web_directory . $width . 'x' . $height . '_' . $this->file;
    $thumbnail_url = substr($thumbnail_url, 0, strrpos($thumbnail_url, '.')) . '.png';
    sfContext::getInstance()->getLogger()->info(sprintf("##### %s", $thumbnail_url));
    if (!$dont_check && (!file_exists(sfConfig::get('sf_web_dir') . $thumbnail_url) || !is_readable(sfConfig::get('sf_web_dir') . $thumbnail_url)))
    {
      $thumbnail_url = '/images/content/no_thumbnail.png';
    }
    return $thumbnail_url;
  }

  /**
   * Return the name of the file downloaded
   * @param Version $version
   * @return string
   */
  public function getDownloadFilename (Version $version = null)
  {
    $filename = Doctrine_Inflector::urlize($this->title);
    $file = $version instanceof Version ? $version->file : $this->file;
    $filename .= substr($file, strrpos($file, '.'));
    return $filename;
  }

  /**
   * Retourne les tags non associé à ce document
   * return Doctrine_Collection
   */
  public function getOtherTags ()
  {
    return Doctrine::getTable('Tag')->createQuery('t')->whereNotIn('id', $this->Tags->getPrimaryKeys())->execute();
  }

  /**
   *
   * @param integer $width
   * @param integer $height
   * @param integer $version_id
   * @return mixed
   */
  public function genThumbnail ($width, $height = null, $version_id = null)
  {
    $thumb_filename = $this->getThumbnailUrl($width, $height, true);
    if (! file_exists(sfConfig::get('sf_web_dir') . $thumb_filename))
    {
      $height = (null === $height) ? $width : $height;

      if (class_exists('finfo_open'))
      {
        $finfo = finfo_open(FILEINFO_MIME_TYPE);
        $mime_type = finfo_file($finfo, $this->getFilePath($version_id));
      }
      else
      {
        $mime_type = mime_content_type($this->getFilePath($version_id));
      }

      $adapterOptions = array();
      if (in_array($mime_type, array('application/pdf')))
      {
        $adapterOptions['extract'] = 1;
      }

      try
      {
        $thumbnail = new sfThumbnail($width, $height, true, true, 75, 'sfImageMagickAdapter', $adapterOptions);
        $thumbnail->loadFile($this->getFilePath($version_id));
        $thumbnail->save(sfConfig::get('sf_web_dir') . $thumb_filename, 'image/png');
      }
      catch(Exception $e)
      {
        sfContext::getInstance()->getLogger()->debug($e->getMessage());
      }
    }
    
    return $thumb_filename;
  }
}
