default:
  http_metas:
    content-type: text/html

  metas:
    title:         Ressources management
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    [jquery, jquery.nmcDropDown.min.js]

  has_layout:     true
  layout:         layout
