<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/10/24 02:16:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=dockeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
