<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dockeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6508 2009-10-14 06:28:49Z jwage $
 */
class User extends BaseUser
{
  /**
   * Secure password
   *
   * @param Doctrine_Event $event
   */
  public function preSave($event)
  {
    if (in_array('password', $this->_modified))
    {
       $this->salt = sha1(date('r'));
       $this->password = sha1($this->salt . $this->password);
    }
  }
  
  /**
   * compare given password
   *
   * @param string $password
   * @return boolean
   */
  public function login ($password)
  {
    return (sha1($this->salt . $password) === $this->password);
  }
}
